VOLUME_SPIKE_MULTIPLIER = 2.0
BREAKOUT_LOOKBACK_MINUTES = 5
MAX_RISE_RATE = 15.0
MIN_TRADE_VALUE = 0
MAX_SPREAD_RATE = 0.3
MAX_DAILY_ENTRY_PER_SYMBOL = 2
PREVIOUS_CANDLE_MAX_DROP_RATE = -2.0

TAKE_PROFIT_RATE = 2.0
STOP_LOSS_RATE = -1.0
MAX_HOLD_MINUTES = 10
STALE_POSITION_MIN_PROFIT_RATE = 0.5
FORCE_EXIT_TIME = "15:15"
NEW_BUY_LIMIT_TIME = "15:00"

MAX_CONSECUTIVE_LOSS_COUNT = 3
